# Generated by Django 5.1.3 on 2024-12-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialticket',
            name='descripcion',
            field=models.TextField(blank=True, default='Descripcion'),
        ),
    ]
