# Generated by Django 5.1.3 on 2024-12-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_historialticket_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12),
        ),
    ]
